#!/bin/sh
# To use this script, the following environment variables must be set
# - GITHUB_EVENT
# The full payload of the github event
# Pull Request payload example:
# https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request
#
# - GITHUB_REF
# A git reference
# More info:
# https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
# This is required, but the renderer doesn't currently use it
#
# - RENDER_REPOSITORY_TOKEN
# A personal access token with a scope "public_repo".
# Generate one here
# https://github.com/settings/tokens/new
# This token should be generated by a user with the ability to trigger
# workflow_dispatch events in the RENDER_REPOSITORY.
#
# - RENDER_REPOSITORY_TOKEN_USER
# The user the RENDER_REPOSITORY_TOKEN was generated by
#
# - RENDER_REPOSITORY
# The username/repository of the GitHub repository that hosts the renderer
# workflow
set -eu
TEMP_FILE="$(mktemp)"
export TEMP_FILE
printf '%s' "${GITHUB_EVENT}" \
| jq --compact-output '{
    "ref": $github_ref,
    "inputs": {
        "pull_request_id": (.pull_request.number),
        "pull_request_event": (. | @json),
    }
}' \
    --arg github_ref "${GITHUB_REF}" \
> "${TEMP_FILE}"

curl \
    --fail \
    --fail-early \
    --request POST \
    --header "Accept: application/vnd.github.v3+json" \
    --user "${RENDER_REPOSITORY_TOKEN_USER}:${RENDER_REPOSITORY_TOKEN}" \
    --post301 --post302 --post303 \
    --data "@${TEMP_FILE}" \
    --url "https://api.github.com/repos/${RENDER_REPOSITORY}/actions/workflows/pull_request.yaml/dispatches"

rm "${TEMP_FILE}"
